spring:
  jwt:
    secret: testSecretKey20230327testSecretKey20230327testSecretKey20230327
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: TestDB
    password: 0924
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging.level:
  org.hibernate.SQL: debug